### ISSUE TITLE
hideKindPrefix will be removed from typedoc-plugin-markdown

### ISSUE THREAD

**Issue by lorenzolewis** [HiDeoo/starlight-typedoc#11]
### Describe the bug

Doing some local dev against the latest in https://github.com/tgreyuk/typedoc-plugin-markdown and was getting this error:

`Tried to set an option (hideKindPrefix) that was not declared.`

This has been removed in https://github.com/tgreyuk/typedoc-plugin-markdown/commit/0271ed1c2f6c7551ccbabefff596b7d32e606d7e

Looks like the plan is to remove `hideKindPrefix` and replace it with `titleTemplate`:

https://github.com/tgreyuk/typedoc-plugin-markdown/blob/next/packages/typedoc-plugin-markdown/docs/usage/options.md#titletemplate

### To Reproduce

Develop a project using the `next` branch of `typedoc-plugin-markdown` as of https://github.com/tgreyuk/typedoc-plugin-markdown/commit/0271ed1c2f6c7551ccbabefff596b7d32e606d7e#diff-f2c035f40366f0be066f365fe4f0e9abc4b5b16c903898aab4800de8ec158c7f

You'll then see the error in the console.

### Expected behavior

Shouldn't error

### How often does this bug happen?

Every time

### Additional Context

Not currently an issue and it doesn't result in a failure, but most likely will affect the output and also adds a bunch of log clutter.

**Comment by HiDeoo** [comment]
Thanks for the report and thorough investigation, super helpful.

I think this change did not make it yet to the `next` tag on npm, so I think we should wait for the change to make it to npm before making any change in the integration as it's not failing like you mentioned and it may change again potentially.

If this makes it to npm as-is, I think what we could do is:

1. Remove the `hideKindPrefix` option in the integration code.
1. Not add anything else as the new `titleTemplate` option defaults to `{title}` which does not include `{kind}` if I am understanding the doc correctly.
1. Release a new minor version that requires at least the version `4.0.0-next.18` of `typedoc-plugin-markdown` as it will prolly be the one including this change (we currently require `4.0.0-next.14`).

**Comment by lorenzolewis** [comment]
Related to the point I made in https://github.com/HiDeoo/starlight-typedoc/pull/10#issuecomment-1656714440 about using a less opinionated default config, if `hideKindPrefix` is removed completely from `starlight-typedoc` then the user can adjust this however they see fit and it wouldn't require being as lock-step with `typedoc-plugin-markdown` and the changes coming through.

**Comment by HiDeoo** [comment]
Makes sense 👍  So I guess the steps described above will go in this direction so two birds with one stone ^^
