### ISSUE TITLE
`@link` not using `relativeURL` override

### ISSUE THREAD

**Issue by lorenzolewis** [HiDeoo/starlight-typedoc#14]
### Describe the bug

When using `{@link}` in the summary block (outside of one of the custom-handled depreciation tags) then it will output the incorrect URL. 

You've tested this in the fixtures but only in the context of a `@depricated` tag: https://github.com/HiDeoo/starlight-typedoc/blob/370bd8ebce26b6d8f73161249442b9f73c749de3/fixtures/src/functions.ts#L18

When using it outside then it results in an invalid URL: https://github.com/lorenzolewis/starlight-typedoc/blob/74acb18161544b6252fd395a880fd09bf2ffd5e3/fixtures/src/functions.ts#L27

The logic path upstream goes to this point from what I can tell: https://github.com/tgreyuk/typedoc-plugin-markdown/blob/ace1b92284a6575141c3ce6d15a8fd7c3813b0e6/packages/typedoc-plugin-markdown/src/theme/resources/partials/comment.parts.ts#L30

However it seems that `context.relativeURL` isn't taking the overridden property. So I'm not 100% sure if this is an issue with upstream and if it is I'm not sure how it would be fixed as everything else that references links seems to be pulling it correctly.

### To Reproduce

See this commit: https://github.com/lorenzolewis/starlight-typedoc/commit/205195146dd9c161440ea6663046b7ffa38c8743

This branch has `starlight-links-validator` added to it to automate checking.

### Expected behavior

This should use the overridden `relativeURL` method.

### How often does this bug happen?

Every time

### Additional Context

This repro is using since this is what's in the example folder `"typedoc-plugin-markdown": "4.0.0-next.16",` but I can confirm the same is happening in `next.17` but haven't checked against `next.18` as it's broken a few things for me unrelated to this.

**Comment by HiDeoo** [comment]
Just published [`v0.3.3`](https://github.com/HiDeoo/starlight-typedoc/releases/tag/v0.3.3) to npm with a fix for this issue.

Thanks again for the report.
