### ISSUE TITLE
Typedoc 0.25 breaks build

### ISSUE THREAD

**Issue by lorenzolewis** [HiDeoo/starlight-typedoc#16]
### Describe the bug

I believe typedoc 0.25 will break your build

### To Reproduce

Try the build, it go boom

### Expected behavior

It shouldn't go boom

### How often does this bug happen?

Every time

### Additional Context

It should be a relatively easy fix, I did this on our repo which is using essentially the same setup as this: https://github.com/tauri-apps/tauri-docs/pull/1437. Lmk if you'd like me to PR it or if you'd to handle it yourself (not sure how you like to deal with dependency versioning).

**Comment by HiDeoo** [comment]
Closed by #17
