### ISSUE TITLE
Broken links when `base` is set in the astro config

### ISSUE THREAD

**Issue by mProjectsCode** [HiDeoo/starlight-typedoc#20]
### Describe the bug

When a `base` is set in the astro config, the internal links between pages no longer work, as they don't include the base.

### To Reproduce

1. create a starlight project and set up the type doc plugin
2. set a `base`
3. run dev server
4. click on an internal link in the generated docs
5. see astros 404 page

### Expected behavior

The link should work and take me to the correct site instead of the 404 page.

### How often does this bug happen?

Every time

### System Info

```json
    "@astrojs/starlight": "^0.15.0",
    "astro": "^4.0.0",
    "sharp": "^0.33.0",
    "starlight-typedoc": "^0.6.0",
    "typedoc": "^0.25.4",
    "typedoc-plugin-markdown": "^4.0.0-next.37",
    "typedoc-plugin-mdn-links": "^3.1.8"
```

### Additional Context

[here](https://github.com/mProjectsCode/obsidian-js-engine-plugin-docs) the repo that i have the problem in.
To get this running you need to also clone the submodule and install the submodules deps. (The submodule uses bun and the docs uses npm. It's kind of a mess 😅.)

**Comment by HiDeoo** [comment]
Thanks for the report 🙌 

This should now be fixed in [`v0.7.0`](https://github.com/HiDeoo/starlight-typedoc/releases/tag/v0.7.0).
