### ISSUE TITLE
incompatible with entryPointStrategy "packages"?

### ISSUE THREAD

**Issue by boneskull** [HiDeoo/starlight-typedoc#23]
### Describe the bug

...or possibly just incompatible with Typedoc v0.52.4.

This is two problems with likely a single root cause.

I have a monorepo with several workspaces, and I use the `packages` `entryPointStrategy` to create a single docs site from them.  This works when `typedoc` is run from the command line (with or without `typedoc-plugin-markdown@next`).

However, this line will _always_ throw an exception with this use case:

https://github.com/HiDeoo/starlight-typedoc/blob/64d367a294106f79cc73b64733bac7061a23ed06/packages/starlight-typedoc/libs/typedoc.ts#L50

This is likely due to a breaking change in how Typedoc creates `ProjectReflection` files, but I don't know if that's due to the breaking changes in how the `packages` `entryPointStrategy` works, or for some other reason.  In this use case, `groups` will _always_ be `undefined`.  I think what you want to get at is deeper in the `ProjectReflection`.

Once this conditional has been commented out, the plugin proceeds to generate the documentation and place it in the desired output directory.  However, the sidebar appears empty (I'm guessing because `groups` is `undefined`).

### To Reproduce

My setup involves a root typedoc config with `entryPointStrategy: 'packages'`, where the `entryPoint`s are relative paths to workspace folders.  Each workspace then has its own Typedoc config containing an `entryPoint` and any other specific configuration.

The configuration for this plugin I'm using is akin to this:

```js
starlightTypeDoc({
  entryPoints: [
    '../workspace-a',
    '../workspace-b',
    '../workspace-c',
  ],
  typeDoc: {
    entryPointStrategy: 'packages'
  },
  tsconfig: '../../tsconfig.json',
})
```

These workspaces live in a `packages/` folder, and my Astro config is in `packages/docs/astro.config.mjs` (thus the relative paths).

### Expected behavior

I'm not sure what I'd expect, exactly.  Certainly, I want the sidebar to display _something_.  It might mean extra nesting in the sidebar?  Ideally, I'd have some control over how I wanted to arrange things without the need to override a component.  Maybe pass in some option to a sidebar configurator which tells it which project to display; I could repeat this for each project.

### How often does this bug happen?

Every time

### System Info

- macOS v14.1.1
- Node.js v20.10.0
- Astro v4.0.6
- @astrojs/starlight v0.15.1
- starlight-typedoc v0.7.0

**Comment by boneskull** [comment]
tangentially related: it's unclear how my existing typedoc config files affect the behavior of this plugin.  They get read, somewhere.

**Comment by HiDeoo** [comment]
Finally got the time to start working on this. The changes require a bit of refactoring to get the proper fixtures in place for this setup but I've managed to reproduce the issue and I seem to have a working prototype adding support for this.

With the following project structure:

```
project
├── package.json
├── packages
│   ├── bar
│   │   ├── package.json
│   │   ├── src
│   │   │   ├── ...
│   │   │   └── ...
│   │   ├── tsconfig.json
│   │   └── typedoc.json
│   └── foo
│   │   ├── package.json
│   │   ├── src
│   │   │   ├── ...
│   │   │   └── ...
│   │   ├── tsconfig.json
│   │   └── typedoc.json
├── tsconfig.base.json
└── tsconfig.json
```

And a plugin configuration like this:

```json
{
  "entryPoints": ["../fixtures/project/packages/*"],
  "tsconfig": "../fixtures/project/tsconfig.json",
  "typeDoc": {
    "entryPointStrategy": "packages"
  }
}
```

I would now get the proper sidebar generated and all links working as expected.

<img width="1203" alt="image" src="https://github.com/HiDeoo/starlight-typedoc/assets/494699/ed125e87-bd3e-41a6-b57f-e06152535c91">

This still requires a bit of work (mostly adding new tests for this), but before going further, as this is not a setup I use myself, I was wondering if your project was available somewhere publicly so I could test this on a real world example?

**Comment by boneskull** [comment]
I'll make a branch for you.

**Comment by boneskull** [comment]
OK, see [this PR](https://github.com/boneskull/midnight-smoker/pull/533).

Also, if you want to push your code somewhere, I can try it myself.

**Comment by HiDeoo** [comment]
Thanks a lot, that was super helpful 🙌 

The sidebar is now properly generating with the new changes:

<img width="290" alt="image" src="https://github.com/HiDeoo/starlight-typedoc/assets/494699/320befae-ce7d-4867-ae6b-bef3c3346406">

> Also, if you want to push your code somewhere, I can try it myself.

Sure, I've pushed a draft PR in https://github.com/HiDeoo/starlight-typedoc/pull/24

**Comment by HiDeoo** [comment]
Fixed with https://github.com/HiDeoo/starlight-typedoc/pull/24 that should be released relatively soon.
