### ISSUE TITLE
latest typedoc-plugin-markdown not working 

### ISSUE THREAD

**Issue by icelattefull** [HiDeoo/starlight-typedoc#29]
### Describe the bug

If I add `typedoc-plugin-markdown 4.0.0-next.43`, I'm getting a couple of errors in `node_modules/starlight-typedoc/libs/theme.ts`, and also astro complains that browsers APIs are being used in server.

The latest that seems to work is `4.0.0-next.38`

### To Reproduce

1. Add typedoc-plugin-markdown 4.0.0-next.43
2. Run `yarn dev`

### Expected behavior

starlight-typedoc is compatible with latest version of typedoc-plugin-markdown

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for your report 🙌 

This should now be fixed in the latest version.
