### ISSUE TITLE
Support for multiple typedoc instance per starlight

### ISSUE THREAD

**Issue by beaussan** [HiDeoo/starlight-typedoc#31]
### Is your feature request related to a problem?

Using starlight-typedoc only allows for a single instance in a astro project since v0.7.0. This means that if you want to document two different entries point separately, you can't anymore since the plugin allow for a single entry in the menu and a single plugin configuration.

### Describe the solution you'd like

Instead of exporting the plugin and the symbol for injecting the menu, we could also expose a plugin creator that can create a new token on the fly so that we can have multiple instance of the same plugin in a single starlight docs

### Describe alternatives you've considered

Doing multiple starlight that are stitched at build time somehow

**Comment by HiDeoo** [comment]
Thanks for your feedback, not a use-case I have so super appreciated! :raised_hands:

[`v0.10.0`](https://github.com/HiDeoo/starlight-typedoc/releases/tag/v0.10.0) now exports a `createStarlightTypeDocPlugin()` function that should enable this use-case and is documented in this new [guide](https://starlight-typedoc.vercel.app/guides/multiple-instances/).

Hope this is close to what you were looking for and allows you to achieve this kind of setup!

**Comment by beaussan** [comment]
Thanks a lot! This works perfectly for me, this will help document monorepos!
