### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by PabloRNC** [HiDeoo/starlight-typedoc#38]
### Describe the bug

I am generating a documentation using typedoc and the markdown plugin. But I'm getting broken links.

As you can see here 
![image](https://github.com/HiDeoo/starlight-typedoc/assets/99443080/3197215a-16de-4a5c-997f-2d745ef3d798)
As you can see there is a /classes route which is making the links to broke. I want so to develop a function which edits the url to remove that unecessary  route.

### To Reproduce

1. Use the typedoc starlight plugin.

2. In the astro config file put the function which call for the plugin 

```js
chatbotTypeDoc({
            entryPoints: ['./twitchapi/packages/chatbot/src/index.ts'],
            tsconfig: './twitchapi/packages/chatbot/tsconfig.json',
            output: 'api/chatbot',
            typeDoc: {
                useCodeBlocks: true,
                parametersFormat: "table",
                propertiesFormat: "table",
                enumMembersFormat: "table",
                typeDeclarationFormat: "table",
                indexFormat: "table",
                expandParameters: true
            }
})
```

Then the md broken links that reference other classes or structures are broken

### Expected behavior

Links aren't broken and redirect to an existing md file

### How often does this bug happen?

Every time

### System Info

- Windows 11. Opera GX

**Comment by HiDeoo** [comment]
Thanks for your report.

Which exact versions of `starlight-typedoc` and `typedoc-plugin-markdown` are you using?

**Comment by PabloRNC** [comment]
Sure.

I have the `v0.10.1` of starlight typedoc and `v4.0.0-next.54` of typedoc-plugin-markdown

**Comment by HiDeoo** [comment]
Thanks, this should be fixed by updating to the version [`0.11.0`](https://github.com/HiDeoo/starlight-typedoc/releases/tag/v0.11.0) of the `starlight-typedoc` plugin which have been released less than 24 hours ago, so probably around the time of the issue.

If not, please let me know and I'll re-open the issue.

**Comment by PabloRNC** [comment]
Sure. I will try. Thanks

**Comment by PabloRNC** [comment]
Works as expected.

**Comment by HiDeoo** [comment]
> Works as expected.

Thanks a lot for taking the time to confirm, super appreciated.

**Comment by PabloRNC** [comment]
Mmm I have another error regarding to broken links.

**Comment by PabloRNC** [comment]
Seems to be with @link tags

**Comment by PabloRNC** [comment]
as you can see I reference `BanOptions` in a link tag and the link is broken.
![image](https://github.com/HiDeoo/starlight-typedoc/assets/99443080/de0f51b5-a84f-4306-a1b0-b322fac9c440)

**Comment by HiDeoo** [comment]
> Seems to be with @link tags

Would you be able to open a new issue with a minimal reproduction of the error? Difficult to understand the issue from a screenshot and jumping in a larger codebase would not be easy so a minimal repro, with just 1 or 2 TypeScript files in a repo and generating the issue would be amazing.

**Comment by PabloRNC** [comment]
Sure

**Comment by PabloRNC** [comment]
Here is the new issue https://github.com/HiDeoo/starlight-typedoc/issues/40
