### ISSUE TITLE
Groups related configuration

### ISSUE THREAD

**Issue by lajbel** [HiDeoo/starlight-typedoc#39]
### Is your feature request related to a problem?

Yes, If I want to have custom gruops or group order I can't (and this is a base TypeDoc feature)

### Describe the solution you'd like

Make this possible

### Additional Context

![image](https://github.com/HiDeoo/starlight-typedoc/assets/71136486/6127b0e9-ab8d-4303-b041-5971e866f791)
![image](https://github.com/HiDeoo/starlight-typedoc/assets/71136486/1bce3d3f-86cd-4f49-80bc-52dbf2bd57ce)

Also doesn't work `excludeGroups`, I think would be great also has custom groups defined by the user using `@group` in jsdoc

Versions:
```
"starlight-typedoc": "^0.11.0",
"typedoc": "^0.25.12",
"typedoc-plugin-markdown": "4.0.0-next.54",
```

**Comment by HiDeoo** [comment]
Thanks for your report.

Additional TypeDoc configuration can be passed down to the plugin using the [`typeDoc`](https://starlight-typedoc.vercel.app/configuration/#typedoc) configuration.

For example, running `pnpm dev` in the `examples/` folder of this repository will generate the following sidebar by default:

<img width="284" alt="SCR-20240416-oozj" src="https://github.com/HiDeoo/starlight-typedoc/assets/494699/5537c3d1-c67d-4286-8b9e-fb055ae9fa13">

Adding the `groupOrder` configuration you mentioned can be done in your Astro configuration file:

```diff
starlightTypeDoc({
  // Other configuration…
  typeDoc: {
+    groupOrder: ['Functions', 'Classes', 'Type Aliases', 'Interfaces'],
  },
}),
```

After these changes, the generated sidebar will look like this:

<img width="285" alt="SCR-20240416-opec" src="https://github.com/HiDeoo/starlight-typedoc/assets/494699/0f0a9874-e271-417c-9d1d-5eb256c8159a">

The order of the groups matches the one provided and extra groups are appended at the end as documented in the [TypeDoc documentation](https://typedoc.org/options/organization/#grouporder).

**Comment by lajbel** [comment]
And custom group names are avaible

**Comment by lajbel** [comment]
https://typedoc.org/options/organization/#categorizebygroup
