### ISSUE TITLE
Badge Support

### ISSUE THREAD

**Issue by DuroCodes** [HiDeoo/starlight-typedoc#44]
### Is your feature request related to a problem?

I'm trying to add a `Generated` badge to my API docs section, and it doesn't seem to work. (Using the spread operator):

```js
sidebars: [
  {
    ...typeDocSidebarGroup,
    badge: {
      text: 'Generated',
      variant: 'note',
    },
  },
  // ...
]
```

### Describe the solution you'd like

An option within `StarlightTypeDocOptions` with the `badge` parameters from `@astrojs/starlight` would be nice. (like being able to set the sidebar as collapsed)

<img width="472" alt="image" src="https://github.com/HiDeoo/starlight-typedoc/assets/47304910/3e3ef0d3-276f-4e08-ac98-a77435cfd0c4">

Would hopefully look like this:

![image](https://github.com/HiDeoo/starlight-typedoc/assets/47304910/48a58878-c1b8-43d0-a9b8-68e96922c117)

**Comment by HiDeoo** [comment]
Thanks for your report :raised_hands:

I just released [`v0.12.1`](https://github.com/HiDeoo/starlight-typedoc/releases/tag/v0.12.1) which includes a fix for this issue.

Using the syntax from your first code block will now work as expected:

<img width="283" alt="SCR-20240511-pynv" src="https://github.com/HiDeoo/starlight-typedoc/assets/494699/44047189-2511-45aa-a5af-be123dfc7bd3">
