### ISSUE TITLE
API Links Different Across Platforms

### ISSUE THREAD

**Issue by DuroCodes** [HiDeoo/starlight-typedoc#46]
### Describe the bug

Whenever my friend using a Windows machine uses the project, there is a difference in the generated API docs.

Using MacOS (probably on any UNIX machine), the paths look like `/api/namespaces/presence/...`, however, on Windows, the paths look like `/api/namespacespresence...`

![image](https://github.com/HiDeoo/starlight-typedoc/assets/47304910/7e53b74f-0537-497f-9eed-25884e35a159)

Oddly enough, it seems like the URL paths still link to the proper page though?

[example](https://deploy-preview-66--sern-docs.netlify.app/v3/api/namespaces/presence/functions/module/#returns)

### To Reproduce

1. Clone a project using `starlight-typedoc`
2. Install & run the project using Windows
3. Look at the API generated docs

### Expected behavior

The paths should be the same regardless of OS

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
👋 Thanks for the feedback

Would you be able to provide a small repro of the issue? Got access to a Windows machine and tried to reproduce but unfortunately, I did not manage to do so. All links were properly generated for me with no differences. I don't really need a lot of code/config, just the bare minimum that would generate a link that change between you and your friend.

**Comment by DuroCodes** [comment]
It happens on this repo: https://github.com/DuroCodes/sern-website; if you look at the commit logs you can see when it gets changed
