### ISSUE TITLE
request: possibility to customize frontmatter for pages and readme (individually)

### ISSUE THREAD

**Issue by favna** [HiDeoo/starlight-typedoc#52]
### Is your feature request related to a problem?

Currently, every page gets some automatic frontmatter which is a good default, however, I want my README specifically to have a different `tableOfContents:` config to set different heading levels. This is currently not possible.

### Describe the solution you'd like

2 new configuration keys for `starlightTypeDoc({ ... })` called `readmeFrontMatter` (which will not do anything if `typeDoc.readme` is not set) and `pageFrontMatter`. These will have all the options as specified on https://starlight.astro.build/reference/frontmatter/ _except_ `editUrl`, `next`, `prev`, and `title` which are set by the library.

### Describe alternatives you've considered

If it would be possible to provide the frontmatter in the README file as linked by `typeDoc.readme` that would work as well

### Additional Context

The relevant code is https://github.com/HiDeoo/starlight-typedoc/blob/3b17bff8efdc84022a6e2daf65069abf8ab1fdce/packages/starlight-typedoc/libs/typedoc.ts#L131-L137

**Comment by HiDeoo** [comment]
Thanks for your feedback.

This should now be supported in the new version [`0.14.0`](https://github.com/HiDeoo/starlight-typedoc/releases/tag/v0.14.0) that I just published. The approach is different from the one you suggested, but the result should be the same with a more powerful and flexible API.

I also added a new [guide](https://starlight-typedoc.vercel.app/guides/frontmatter/) to the documentation on how to customize the frontmatter of generated pages.
