### ISSUE TITLE
Custom frontmatter cannot be added via TypeDoc plugin

### ISSUE THREAD

**Issue by Fevol** [HiDeoo/starlight-typedoc#53]
### Describe the bug

You are not able to specify additional frontmatter using TypeDoc plugins, making it very difficult to, for example, automatically add badges to the frontmatter of a file based on whether it has a `@todo` tag.

### To Reproduce

1. Add custom plugin script
```js
// ./plugins/badge-plugin.js
import { MarkdownRendererEvent, MarkdownPageEvent} from "typedoc-plugin-markdown";

export function load(app) {
    app.renderer.on(
        MarkdownPageEvent.END,
        /** @param {MarkdownPageEvent} page */
        (page) => {
            if (page.model.comment?.blockTags.some(tag => tag.tag === "@todo")) {
                page.frontmatter = {
                    sidebar: '\n  badge:\n    text: TODO\n    variant: tip',
                    ...page.frontmatter,
                };
            }
        }
    );
}
```
2. Add plugin to `typedoc` config
```js
export default defineConfig({
    integrations: [
        starlight({
            plugins: [
                starlightTypeDoc({
                    typeDoc: {
                        plugin: [
                            './plugins/badge-plugin.js',
                        ],
                    },
                }),
            ]
        }),
    ],
})
```
3. Run `astro dev`

### Expected behavior

It seems like in the final markdown processing step, the frontmatter included with the `PageReflection` is not included, see:
https://github.com/HiDeoo/starlight-typedoc/blob/3b17bff8efdc84022a6e2daf65069abf8ab1fdce/packages/starlight-typedoc/libs/typedoc.ts#L131-L137

A simple fix would be to just add a destructuring assignment to the code, here's how I attempted to fix this:
```js
  event.contents = addFrontmatter(event.contents, {
    editUrl: false,
    next: pagination,
    prev: pagination,
    // Wrap in quotes to prevent issue with special characters in frontmatter
    title: `"${event.model.name}"`,
    ...event.frontmatter
  })
```

Another nice addition would be to have a nested JSON be correctly formatted to YAML inside `addFrontmatter`.

### How often does this bug happen?

Every time

### System Info

- `typedoc`: `0.26.5`
- `typedoc-plugin-markdown`: `4.1.0`
- `starlight-typedoc`: `0.13.1`

### Additional Context

Code repository: https://github.com/Fevol/obsidian-typings-website

**Comment by Fevol** [comment]
I sadly failed to read the other issues before posting this one.

This is a duplicate of #52, but I'll keep it open for the extra info/plugin example.

**Comment by HiDeoo** [comment]
> I sadly failed to read the other issues before posting this one.

No problem at all, thanks for the detailed report :raised_hands:

This should now be fixed in the new version [`0.14.0`](https://github.com/HiDeoo/starlight-typedoc/releases/tag/v0.14.0) that I just published.

I also added a new [guide](https://starlight-typedoc.vercel.app/guides/frontmatter/) to the documentation on how to customize the frontmatter of generated pages.

**Comment by Fevol** [comment]
Thank you very much for the quick response, this package has been a blast to use!

**Comment by Fevol** [comment]
Just noting this here if anyone else comes across this issue. The patch worked perfectly at first, but at some point, there seems to be a race condition between `starlight-typedoc` and `typedoc-plugin-frontmatter`; where the defaults (`title`, `editUrl`, `next`, `prev`) do not get added and you might get a `does not match collection schema (title required)` error. I'm guessing that `typedoc-plugin-frontmatter` fetches the frontmatter first, before `starlight-typedoc` gets to add it. Strangely, the frontmatter of my plugin _does_  get added, so I don't get what's going on there. Perhaps a oddity where TypeDoc orders the `MarkdownPageEvent.BEGIN` events in a weird way? Sadly, I haven't been able to find any resources to force the order.

Either way, I have not been able to find or bisect the actual change/issue, so it could very well be that my hypothesis is wrong. For now, I have temporarily bypassed the crash by adding the following to the last line of my plugin:
```
page.frontmatter = {
    title: page.model.name,
    editUrl: false,
    next: true,
    prev: true,
    ...page.frontmatter
}
```

**Comment by favna** [comment]
I am experiencing the same issue as @Fevol. 

Furthermore, to continue from my feature request from #52 I would also like to note that the current implementation doesn't satisfy the feature request entirely because `README.md` is never covered. I logged the `page.model.url` for every entry and notably `README.md` is missing:

![ishare-1722690577](https://github.com/user-attachments/assets/25f5e881-b41d-4587-b5e3-f264faf5d6f6)

![ishare-1722690634](https://github.com/user-attachments/assets/0f861770-e1c3-4c97-b8c2-1916409b4b19)

**Comment by Fevol** [comment]
Hi @HiDeoo, would you happen to know more about this issue? Should I open a separate issue thread for this? 
It is pretty likely that this is a misconfiguration on our end, but I haven't been able to sus out what it is precisely.

**Comment by HiDeoo** [comment]
Thanks for the ping, almost missed this one.

I haven't been able to reproduce this one personally. I tried using the repo `Fevol/obsidian-typings-website` you shared above altho I'm not sure how to start the project:

- I cloned the repo
- Fetch submodules
- Run `npm i` in the `obsidian-typings` folder
- Run `bun run preprocess` at the root level
- Run `bun run dev` 

But I'm getting a lot of errors, so I'm not sure if I'm doing it right. Could you provide an easier reproducible example or some instructions on how I should get started with the project?

**Comment by Fevol** [comment]
Ah apologies, I have never pushed the `skipLibCheck: true` toggle to the `tsconfig.json`, this should be added with the latest commit. Other than that, the steps you have posted are all correct. If that doesn't work either, I'll gladly try to make a small repro repository.

**Comment by HiDeoo** [comment]
Thanks for the detailed instructions, got it working now.

I think I manage to find the problem and a fix for it. I'll take the time tomorrow morning to test a bit more and figure out a test for it as I've been using your code base only to debug the issue so far.

Also, for w/e reason, your condition `if (page.model.comment?.blockTags.some((tag) => tag.tag === "@todo")) {` was not working for me so I switch to another tag, e.g. `if (page.model.comment?.blockTags.some((tag) => tag.tag === "@source")) {`.

With no plugin, only `typedoc-plugin-frontmatter` or all your plugins, it's now working as expected. Here is a screenshot of the badges added when the `@source` tag is detected:

<img width="1129" alt="image" src="https://github.com/user-attachments/assets/bc195026-dd7b-4c31-b12b-9745ca5aff5d">

I'm hoping to have a PR ready with the fix tomorrow.

**Comment by Fevol** [comment]
> Small unrelated feedback in case it can help: `npm-run-all` is not a dependency so `bun run setup` was failing before installing it.

Thanks for pointing that out! It seems like I ran the `bun i npm-run-all` install command in the wrong directory... 🙈

**Comment by HiDeoo** [comment]
Turns out the reproduction was a bit difficult as the issue was due to a change in the latest patch version of TypeDoc. This should now be fixed in the [latest release](https://github.com/HiDeoo/starlight-typedoc/releases/tag/v0.15.0).

**Comment by favna** [comment]
Thanks @HiDeoo! I updated my code [here](https://github.com/skyra-project/discord-components/commit/fe237595f8af20a11d9d38e872ee1ee1af61b35f) and it works perfectly.

**Comment by Fevol** [comment]
Many thanks for the fix @HiDeoo! I can also confirm that everything works perfectly now.
