### ISSUE TITLE
bug: descriptions are being dropped for "other" category symbols

### ISSUE THREAD

**Issue by favna** [HiDeoo/starlight-typedoc#55]
### Describe the bug

For the project https://github.com/skyra-project/discord-components I use `public accessor` because that's how Lit Element works when using TC39 decorators. When parsing this with regular typedoc (config below) the accessor still do get put into the "other" category just like starlight-typedoc does, however unlike starlight-typedoc, regular typedoc still retains descriptions.

Relevant code: https://github.com/skyra-project/discord-components/blob/e34e27efff4d1fb3d41def616bed017d97964d34/packages/core/src/components/discord-audio-attachment/DiscordAudioAttachment.ts#L124-L169

From the HTML generated by Typedoc:
![ishare-1722689243](https://github.com/user-attachments/assets/8e1f7624-f6f9-4a29-965f-7546116fda76)

From the HTML generated by starlight-typedoc:

![ishare-1722689271](https://github.com/user-attachments/assets/cbd0b693-b102-4789-85f2-d1809ee301a7)

The typedoc config used for the typedoc HTML (at path `packages/core/typedoc.json`):
```json
{
	"readme": "../documentation/src/assets/README.md",
	"excludeExternals": true,
	"githubPages": true,
	"disableSources": true,
	"entryPoints": ["./src/index.ts"],
	"tsconfig": "./src/tsconfig.json",
	"basePath": "/",
    "out": "./docs",
    "cleanOutputDir": true
}
```

### To Reproduce

1. Clone https://github.com/skyra-project/discord-components
1. Run `git switch bugreport/starlight-typedoc-other-descriptions` to switch to a branch with some files prepared for this bug report
1. Run `yarn install --immutable`
1. Run `yarn build`
1. Run `yarn bug:starlight`
1. Navigate to http://localhost:4321/api/classes/discordaudioattachment/#bytes
1. In a new terminal run `yarn bug:typedoc`, this will build with regular typedoc and start an HTTP server on port 8090
1. Navigate to http://localhost:8090/classes/DiscordAudioAttachment.html#bytes

### Expected behavior

The tsdoc comments from accessors (other category symbols) aren't dropped

### How often does this bug happen?

Every time

### System Info

```
  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 70.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.0 - /private/var/folders/jy/w45_1th97698mzgm_nsfl35w0000gn/T/xfs-2eeb1fb6/node
    Yarn: 4.3.1 - /private/var/folders/jy/w45_1th97698mzgm_nsfl35w0000gn/T/xfs-2eeb1fb6/yarn
    npm: 10.8.1 - ~/.volta/tools/image/node/22.4.0/bin/npm
    pnpm: 9.6.0 - ~/.volta/bin/pnpm
    bun: 1.1.21 - /opt/homebrew/bin/bun
  Browsers:
    Edge: 127.0.2651.86
    Safari: 17.5
  Packages:
    @astrojs/lit: ^4.3.0,
    @astrojs/starlight: 0.25.3,
    astro: 4.12.3,
    starlight-typedoc: 0.13.1,
    typedoc: 0.26.5,
    typedoc-plugin-markdown: 4.2.3
```

### Additional Context

I am not sure if this is a problem with typedoc-plugin-markdown or with starlight-typedoc. In case it's with typedoc-plugin-markdown I will create an issue there, so please let me know.

**Comment by HiDeoo** [comment]
> I am not sure if this is a problem with typedoc-plugin-markdown or with starlight-typedoc. In case it's with typedoc-plugin-markdown I will create an issue there, so please let me know.

To test this, I manually installed `typedoc-plugin-markdown` to the core package and added the plugin to the `packages/core/typedoc.json` file:

```diff
{
	"readme": "../documentation/src/assets/README.md",
	"excludeExternals": true,
	"githubPages": true,
	"disableSources": true,
	"entryPoints": ["./src/index.ts"],
	"tsconfig": "./src/tsconfig.json",
	"basePath": "/",
	"out": "./docs",
-	"cleanOutputDir": true
+	"cleanOutputDir": true,
+	"plugin": ["typedoc-plugin-markdown"]
}
```

When running `yarn bug:typedoc` (so no `starlight-typedoc`), for the `DiscordAudioAttachment` class, I get the same output:

```md
***

### bytes

***

### bytesUnit

***

### href

***
```

I think this hints that the problem may be with `typedoc-plugin-markdown` and not with `starlight-typedoc` in this specific case.
