### ISSUE TITLE
Unable to use this plugin when Starlight config uses shorthand sidebar items

### ISSUE THREAD

**Issue by rdpacheco** [HiDeoo/starlight-typedoc#61]
### Describe the bug

Starlight allows users to configure their sidebar items using full objects 
```js
...
sidebar: [
  label: 'Getting started',
  items: [
    { label: 'My page', link: 'guides/my-page' }
  ]
]
...
```

They also support a shorthand version that is just a `string`. This `starlight-typedoc` plugin errors out and fails when using the shorthand:
```js
...

sidebar: [
  label: 'Getting started',
  items: [
    'guides/my-page'
  ]
]
...
```

Error produced:
`Cannot use 'in' operator to search for 'items' in guides/my-page`

### To Reproduce

1. Follow this repo's instructions on how to install this plugin
2. Use shorthand sidebar configuration
3. Build

This is my full sidebar config block:
```js

sidebar: [
  {
    label: 'Get Started',
      items: [
        'guides/getting-started/quick-start',
      ],
  },
    
  // Add the generated sidebar group to the sidebar.
  typeDocSidebarGroup,
],
```

### Expected behavior

I expect my Starlight app to build successfully and generate the sidebar with my manually configured (shorthand) pages as well as the auto generated typedoc section

### How often does this bug happen?

Every time

### Additional Context

Changing the `isSidebarManualGroup` function to this fixes the issue:
```ts
// libs/starlight.ts

function isSidebarManualGroup(item: NonNullable<StarlightUserConfigSidebar>[number]): item is SidebarManualGroup {
  return typeof item === "string"
    ? false
    : 'items' in item
}
```

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands: 

I just published the version [`0.17.0`](https://github.com/HiDeoo/starlight-typedoc/releases/tag/v0.17.0) that should fix the issue.
