### ISSUE TITLE
Extend typeDoc config type

### ISSUE THREAD

**Issue by lorenzolewis** [HiDeoo/starlight-typedoc#8]
### Is your feature request related to a problem?

Improves DX when wanting to use some of the `typedoc-plugin-markdown` options in the `typeDoc` config object. Right now there's no completion for this.

### Describe the solution you'd like

Import plugin options from `typedoc-plugin-markdown`:

```ts
import type { PluginOptions } from 'typedoc-plugin-markdown'
```

Union that with the `typeDoc` config here: 
https://github.com/HiDeoo/starlight-typedoc/blob/81fe9d426138a6623b62b173c7b93be7f2230ca8/packages/starlight-typedoc/src/index.ts#L65

**Comment by HiDeoo** [comment]
Excellent idea.

If I remember correctly, when I started working on this, the options were not exported but the version `4.0.0-next.14` contains `Export plugin options` so this turns out perfectly.

Thanks for the feedback.

**Comment by HiDeoo** [comment]
[`v0.3.1`](https://github.com/HiDeoo/starlight-typedoc/releases/tag/v0.3.1) including the changes for this issue and #7 has been published to npm.

Thanks again.
